### ISSUE TITLE
Using with a custom trained version of yolo5

### ISSUE THREAD

**Issue by lizozom** [nihui/ncnn-webassembly-yolov5#11]
I have used Colab to train yolo5 to detect custom objects using the official [Ultralytics Colab](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb).

Could you please help me understand how to convert the model into the appropriate format to be consumed by this example?

**Comment by lizozom** [comment]
I was able to export the model from py > onnx > ncnn
However it seems like the input and output shape of the model generated by the colab is entirely different than the one expected by the model. Still trying to figure it out.

**Comment by aravamu2** [comment]
> I was able to export the model from py > onnx > ncnn However it seems like the input and output shape of the model generated by the colab is entirely different than the one expected by the model. Still trying to figure it out.

@lizozom I was wondering how you resolved this issue. Thanks!
